### ISSUE TITLE
get a failed when running the obi script

### ISSUE THREAD

**Issue by samusa9** [RittmanMead/scripts#20]
OBIEE version: 11.1.1.9.0.150415.1247

Can you please advise me on where i am going wrong. 

 Checking WLS Admin Server: listening on port 7001         [  OK  ]
 Checking WLS Node Manager: listening on port 9556         [  OK  ]
 Checking WLS Managed Server: listening on port 8205 9704  [  OK  ]

** OBIEE login page is not accessible **                   [FAILED]
  Login to the WLS Console and check : 
   - the Managed Server state is RUNNING
   - the Application Deployment "analytics" is running
 Checking OPMN: listening on port 9500 9501                [  OK  ]
	All OPMN-managed BI Components are running         [  OK  ]

**Comment by rmoff** [comment]
Can you access the login page through the browser? If so, can you login? 
If you look in WLS console, what's the status of the bi_server1?

**Comment by samusa9** [comment]
the status and the bi_server is up and running.

**Comment by samusa9** [comment]
but i can not access the xmlpserver and the analytics url

**Comment by rmoff** [comment]
What's the status of the analytics and xmlpserver application deployments in EM?

**Comment by samusa9** [comment]
the analytics is OK

**Comment by samusa9** [comment]
and the xmlpserver is OK, but cannot access both URL

**Comment by rmoff** [comment]
What error do you get when you try to access the URL?

**Comment by samusa9** [comment]
I logged into the obiee em url, there the bi_server is not running, it was showing down. when i put in the URL. I was getting a 404 error. so there is something that is not really working, so i removed the script to try again.

**Comment by rmoff** [comment]
Sounds like an issue with your installation. Please reopen if there is an issue with the script that you can reproduce.
